### ISSUE TITLE
issue on guild invite creation

### ISSUE THREAD

**Issue by nategoldsborough** [Antares-Network/AntaresBot#22]
```js
10 Jan 2021 12:39:53.238129 <190>1 2021-01-10T18:39:52.792097+00:00 app worker.1 - - DiscordAPIError: Unknown Channel
    at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
10 Jan 2021 13:21:46.698129 <190>1 2021-01-10T19:21:46.214426+00:00 app worker.1 - - DiscordAPIError: Unknown Channel
    at RequestHandler.execute (/app/node_modules/discord.js/src/rest/RequestHandler.js:154:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async RequestHandler.push (/app/node_modules/discord.js/src/rest/RequestHandler.js:39:14)
    at async createLink (/app/commands/serverInvites.js:19:30)
```

The output that I get:
```nano
Guild Name: SAMPLEGUILD
Invite link: undefined
```

**Comment by nategoldsborough** [comment]
I think this is resolved. If not I will reopen.
